1343 result initial sort
GridProtectionAlliance/SEBrowser pull request #49
Opened 2023-06-28 14:39 UTC by gpinkley

Ticket_1343 "Currently the sort column and order is not indicated on a new search. The arrow should be present to show the user how results are being sorted. The initial sort should be chronologically from oldest to newest." This was resolved by, In EventSearchSlice.ts, updateing initialState > SortField to sort by "Time" instead of "FIleStartTime". Removed some unused references. Updated the verbiage in the message at the bottom of the results table.

2023-06-28 21:04 UTC, elwills commented on SEBrowser/Scripts/TSX/Components/EventSearch/EventSearchList.tsx
> +                        Only the first {data.length} chronological results are shown - please narrow your search or increase the number of results in the application settings
Please add a period to the end of the message for UI consistency. Same in `EventSearchMagDur.tsx`.

2023-06-28 21:10 UTC, elwills requested changes

2023-06-28 21:10 UTC, elwills commented on SEBrowser/Scripts/TSX/Components/EventSearch/EventSearchSlice.ts
> +
Please remove the extra empty lines.

2023-06-29 16:13 UTC, clackner-gpa approved these changes

2023-06-29 16:15 UTC, elwills approved these changes

2023-06-29 16:15 UTC, merged