Updated time filter to use gemstone version
GridProtectionAlliance/SEBrowser pull request #97
Opened 2024-07-19 19:30 UTC by Tenacs

2025-01-28 19:23 UTC, gcsantos-gpa requested changes
I think you are being a little over-zealous on what formating constants you replace. I don't think you can use one global constant everywhere since different components expect different formats and different formats make sense in different places. I left some comments on some places where I saw this done but I know for sure I didn't comment on everything. Can you go through and only replace where it makes sense for the setting? What is the setting meant to unifiy? The server format we get back from the controllers? That we send to the controllers?

2025-01-28 19:23 UTC, gcsantos-gpa commented on SEBrowser/Scripts/TSX/Components/TrendData/TrendPlot/LineGraph.tsx
> +        const endTime: number = endMoment.valueOf();
```suggestion
        const startTime: number = moment.utc(props.TimeFilter.start, dateTimeFormat).valueOf();
        const endTime: number = moment.utc(props.TimeFilter.end, dateTimeFormat).valueOf();
```
No need to have this assignment, it makes it a little more hard to read in my opinion.

2025-01-28 19:23 UTC, gcsantos-gpa commented on SEBrowser/Scripts/TSX/Components/TrendData/Components/TrendMarkerTable.tsx
> -    const momentFormat = "DD HH:mm:ss.SSS";
This replacement doesn't work, moment format isn't the same as datetimeformat from settings.

2025-01-28 19:23 UTC, gcsantos-gpa commented on SEBrowser/Scripts/TSX/Components/TrendData/Settings/OverlayTabs/PlotSettingsTab.tsx
> +                <TimeFilter filter={props.Plot.TimeFilter/* convertTimeFilter(props.Plot.TimeFilter) */} showQuickSelect={false}
What's with this commented out code?

2025-01-28 19:23 UTC, gcsantos-gpa commented on SEBrowser/Scripts/TSX/Components/TrendData/TrendDataNavbar.tsx
> +        const startMoment = moment(timeFilter.start); // These default to the date+time format
Please don't use default moment formats, it can lead to unexpected bugs. Be explicit

2025-01-28 19:23 UTC, gcsantos-gpa commented on SEBrowser/Scripts/TSX/Settings.tsx
> -    },
Why are we dropping support for centered time window format?

2025-01-29 14:40 UTC, collins-self commented on SEBrowser/Scripts/TSX/Settings.tsx
> -    },
I believe that was the main update I was doing to this branch. Christoph said to do away with it, and just handle its conversion to the back end. (If it's still using that format in the back end)

2026-07-29 13:21 UTC, closed without merging